# DataFrame Assignment

In [1]:
import pandas as pd

### 1. Create a DataFrame:

In [2]:
df = pd.DataFrame({
    'Order ID': [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
    'Customer': ['Alice', 'Bob', 'Charlie', 'Alice', 'David', 'Charlie', 'Bob', 'Alice'],
    'Product' : ['Laptop', 'Phone', 'Chair', 'Table', 'Laptop', 'Phone', 'Chair', 'Phone'],
    'Category': ['Electronics', 'Electronics', 'Furniture', 'Furniture', 'Electronics', 'Electronics', 'Furniture', 'Electronics'],
    'Quantity': [2, 1, 4, 1, 1, 2, 2, 1],
    'Price'   : [800, 500, 100, 250, 800, 500, 100, 500],
    'Total Sales': [1600, 500, 400, 250, 800, 1000, 200, 500]
})
df

   Order ID Customer Product     Category  Quantity  Price  Total Sales
0      1001    Alice  Laptop  Electronics         2    800         1600
1      1002      Bob   Phone  Electronics         1    500          500
2      1003  Charlie   Chair    Furniture         4    100          400
3      1004    Alice   Table    Furniture         1    250          250
4      1005    David  Laptop  Electronics         1    800          800
5      1006  Charlie   Phone  Electronics         2    500         1000
6      1007      Bob   Chair    Furniture         2    100          200
7      1008    Alice   Phone  Electronics         1    500          500

### 2. Add a New Column:
    Add a column Discount that gives a 10% discount on total
    sales.

In [3]:
df['Discount'] = df['Total Sales'] * 0.1
df

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0
1,1002,Bob,Phone,Electronics,1,500,500,50.0
2,1003,Charlie,Chair,Furniture,4,100,400,40.0
3,1004,Alice,Table,Furniture,1,250,250,25.0
4,1005,David,Laptop,Electronics,1,800,800,80.0
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0
6,1007,Bob,Chair,Furniture,2,100,200,20.0
7,1008,Alice,Phone,Electronics,1,500,500,50.0

### 3. Add a New Row:
    Add a new sales record: Order ID = 1009, 
    Customer = "Eve", Product = "Tablet", Category = "Electronics",
    Quantity = 1, Price = 300, Total Sales = 300.

df.loc[len(df)] = [1009, 'Eve', 'Tablet', 'Electronics', 1, 300, 300, 300*0.1]
df

### 4. Filter Data:
    Retrieve only the sales records where the Category is
    "Electronics".

In [4]:
df[df['Category'] == 'Electronics']

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0
1,1002,Bob,Phone,Electronics,1,500,500,50.0
4,1005,David,Laptop,Electronics,1,800,800,80.0
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0
7,1008,Alice,Phone,Electronics,1,500,500,50.0

### 5. Selection:
    Select the Customer and Total Sales columns.

In [5]:
df[['Customer','Total Sales']]

  Customer  Total Sales
0    Alice         1600
1      Bob          500
2  Charlie          400
3    Alice          250
4    David          800
5  Charlie         1000
6      Bob          200
7    Alice          500

### 6. Grouping:
    Group the data by Customer and calculate the total sales per
    customer.

In [6]:
df.groupby('Customer')['Total Sales'].sum()

Customer
Alice      2350
Bob         700
Charlie    1400
David       800
Name: Total Sales, dtype: int64

### 7. Sorting:
    Sort the DataFrame based on Total Sales in descending
    order.

In [7]:
df.sort_values('Total Sales', ascending=False)

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0
4,1005,David,Laptop,Electronics,1,800,800,80.0
1,1002,Bob,Phone,Electronics,1,500,500,50.0
7,1008,Alice,Phone,Electronics,1,500,500,50.0
2,1003,Charlie,Chair,Furniture,4,100,400,40.0
3,1004,Alice,Table,Furniture,1,250,250,25.0
6,1007,Bob,Chair,Furniture,2,100,200,20.0

### 8. Apply Function:
    Apply a lambda function to create a new column Sales
    Category, where values are labeled as "High" if Total Sales >
    1000, otherwise "Low".

In [8]:
def check_sales(x):
    if x > 500:
        return "High"
    else:
        return "Low"

In [9]:
df['Sales Category'] = df['Total Sales'].apply(check_sales)
df

,Order ID,Customer,Product,Category,Quantity,Price,Total Sales,Discount,Sales Category
0,1001,Alice,Laptop,Electronics,2,800,1600,160.0,High
1,1002,Bob,Phone,Electronics,1,500,500,50.0,Low
2,1003,Charlie,Chair,Furniture,4,100,400,40.0,Low
3,1004,Alice,Table,Furniture,1,250,250,25.0,Low
4,1005,David,Laptop,Electronics,1,800,800,80.0,High
5,1006,Charlie,Phone,Electronics,2,500,1000,100.0,High
6,1007,Bob,Chair,Furniture,2,100,200,20.0,Low
7,1008,Alice,Phone,Electronics,1,500,500,50.0,Low

### 9. Save DataFrame:
    Save the final DataFrame as a CSV file named sales_data.csv.

In [10]:
df.to_csv('sales_data.csv', index=False)