In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(np.random.randint(1,100,(20,5)),columns=['M1', 'M2', 'M3', 'M4', 'M5'])
df

    M1  M2  M3  M4  M5
0   20  17  15  51   3
1   38  72  68  58  85
2    6  77  37  74  69
3   79  18  32  99  35
4   59  65  69  73   7
5   75  76  62  92  10
6   45  67  41  98  89
7    3  16  98  21  39
8    8  58  59  19  34
9   55  21  62  11  39
10  19  31  80  41  43
11  93  50  57  86  78
12  20  94  96  79  52
13  36   7  23  50  84
14  71  78  22  60  37
15  30  64  30  27  26
16  93  44  10  58  72
17  94   6  48  15  89
18  14  50  64  46  67
19  37  27  79  52  50

In [3]:
df.sum()

M1     895
M2     938
M3    1052
M4    1110
M5    1008
dtype: int64

In [4]:
df.sum() # Gives of columns by default

M1     895
M2     938
M3    1052
M4    1110
M5    1008
dtype: int64

In [5]:
df.sum(axis=1) # Gives of rows

0     106
1     321
2     263
3     263
4     273
5     315
6     340
7     177
8     178
9     188
10    214
11    364
12    341
13    200
14    268
15    177
16    277
17    252
18    241
19    245
dtype: int64

In [6]:
df["Total"] = df.sum(axis=1)
df

    M1  M2  M3  M4  M5  Total
0   20  17  15  51   3    106
1   38  72  68  58  85    321
2    6  77  37  74  69    263
3   79  18  32  99  35    263
4   59  65  69  73   7    273
5   75  76  62  92  10    315
6   45  67  41  98  89    340
7    3  16  98  21  39    177
8    8  58  59  19  34    178
9   55  21  62  11  39    188
10  19  31  80  41  43    214
11  93  50  57  86  78    364
12  20  94  96  79  52    341
13  36   7  23  50  84    200
14  71  78  22  60  37    268
15  30  64  30  27  26    177
16  93  44  10  58  72    277
17  94   6  48  15  89    252
18  14  50  64  46  67    241
19  37  27  79  52  50    245

In [7]:
df.loc[20] = [50, 50, 40, 60, 40, 240]

In [8]:
df

    M1  M2  M3  M4  M5  Total
0   20  17  15  51   3    106
1   38  72  68  58  85    321
2    6  77  37  74  69    263
3   79  18  32  99  35    263
4   59  65  69  73   7    273
5   75  76  62  92  10    315
6   45  67  41  98  89    340
7    3  16  98  21  39    177
8    8  58  59  19  34    178
9   55  21  62  11  39    188
10  19  31  80  41  43    214
11  93  50  57  86  78    364
12  20  94  96  79  52    341
13  36   7  23  50  84    200
14  71  78  22  60  37    268
15  30  64  30  27  26    177
16  93  44  10  58  72    277
17  94   6  48  15  89    252
18  14  50  64  46  67    241
19  37  27  79  52  50    245
20  50  50  40  60  40    240

In [16]:
df.drop("Total", axis=1, inplace=True)

In [17]:
df

    M1  M2  M3  M4  M5
0   20  17  15  51   3
1   38  72  68  58  85
2    6  77  37  74  69
3   79  18  32  99  35
4   59  65  69  73   7
5   75  76  62  92  10
6   45  67  41  98  89
7    3  16  98  21  39
8    8  58  59  19  34
9   55  21  62  11  39
10  19  31  80  41  43
11  93  50  57  86  78
12  20  94  96  79  52
13  36   7  23  50  84
14  71  78  22  60  37
15  30  64  30  27  26
16  93  44  10  58  72
17  94   6  48  15  89
18  14  50  64  46  67
19  37  27  79  52  50
20  50  50  40  60  40

In [18]:
df.insert(5, "Total", df.sum(axis=1))

In [19]:
df

    M1  M2  M3  M4  M5  Total
0   20  17  15  51   3    106
1   38  72  68  58  85    321
2    6  77  37  74  69    263
3   79  18  32  99  35    263
4   59  65  69  73   7    273
5   75  76  62  92  10    315
6   45  67  41  98  89    340
7    3  16  98  21  39    177
8    8  58  59  19  34    178
9   55  21  62  11  39    188
10  19  31  80  41  43    214
11  93  50  57  86  78    364
12  20  94  96  79  52    341
13  36   7  23  50  84    200
14  71  78  22  60  37    268
15  30  64  30  27  26    177
16  93  44  10  58  72    277
17  94   6  48  15  89    252
18  14  50  64  46  67    241
19  37  27  79  52  50    245
20  50  50  40  60  40    240

In [20]:
df["M1"]

0     20
1     38
2      6
3     79
4     59
5     75
6     45
7      3
8      8
9     55
10    19
11    93
12    20
13    36
14    71
15    30
16    93
17    94
18    14
19    37
20    50
Name: M1, dtype: int64