# DataFrame
## Introduction
1. 2D data structure in pandas
2. powerful features
3. size-mutable
4. heterogenous
5. tabular data(rows & columns)

In [1]:
import pandas as pd

In [4]:
df = pd.DataFrame([10, 20, 30, 40])
df

    0
0  10
1  20
2  30
3  40

In [6]:
df = pd.DataFrame([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
df

    0
a  10
b  20
c  30
d  40

In [8]:
df = pd.DataFrame([10, 20, 30, 40], index=['a', 'b', 'c', 'd'], columns=['First'])
df

   First
a     10
b     20
c     30
d     40

In [10]:
students = pd.DataFrame({"Roll no":[1, 2, 3], "Name":["Ganesh", "Vishal", "Gaurav"]})
students

   Roll no    Name
0        1  Ganesh
1        2  Vishal
2        3  Gaurav

In [13]:
students.set_index("Roll no")

           Name
Roll no
1        Ganesh
2        Vishal
3        Gaurav

In [15]:
data = pd.read_csv("C:/Users/ganes/OneDrive/Desktop/FBS/Database files/Missing Value Fortune_10.csv")
data

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
2,3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
4,5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%
5,6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
6,7,Yes,Cityace,IT Service,NaN,NaN,"6,249,498 Dollars",3005116.0,6%
7,8,No,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
9,10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [16]:
data.set_index('ID')

,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
ID,,,,,,,,
1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%
6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
7,Yes,Cityace,IT Service,NaN,NaN,"6,249,498 Dollars",3005116.0,6%
8,No,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [17]:
data

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
2,3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
4,5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%
5,6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
6,7,Yes,Cityace,IT Service,NaN,NaN,"6,249,498 Dollars",3005116.0,6%
7,8,No,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
9,10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [21]:
data.loc[1:5]

,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
ID,,,,,,,,
1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%

In [24]:
data.iloc[1:5]

,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
ID,,,,,,,,
2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%

In [25]:
data.iloc[:, 0:6]

,Date,Name,Companies,Inception,Revenue,Expenses
ID,,,,,,
1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars"
2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN
3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars"
4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars"
5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars"
6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars"
7,Yes,Cityace,IT Service,NaN,NaN,"6,249,498 Dollars"
8,No,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars"
9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars"
10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars"

In [28]:
data["Name"]

ID
1            Lamtone
2          Stripfind
3                NaN
4           Mattouch
5          Techdrill
6           Techline
7            Cityace
8     Kayelectronics
9            Ganzlax
10      Transtraxlax
Name: Name, dtype: str

In [29]:
data.columns

Index(['Date', 'Name', 'Companies', 'Inception', 'Revenue', 'Expenses',
       'Profit', 'Growth'],
      dtype='str')

In [31]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 1 to 10
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       10 non-null     str
 1   Name       9 non-null      str
 2   Companies  10 non-null     str
 3   Inception  8 non-null      float64
 4   Revenue    9 non-null      str
 5   Expenses   9 non-null      str
 6   Profit     9 non-null      float64
 7   Growth     10 non-null     str
dtypes: float64(2), str(6)
memory usage: 772.0 bytes

In [32]:
data.head()

,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
ID,,,,,,,,
1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%

In [33]:
data.head(6)

,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
ID,,,,,,,,
1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%
6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%

In [35]:
data.tail()

,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
ID,,,,,,,,
6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
7,Yes,Cityace,IT Service,NaN,NaN,"6,249,498 Dollars",3005116.0,6%
8,No,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [36]:
data.tail(2)

,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
ID,,,,,,,,
9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [38]:
data.describe()

        Inception        Profit
count     8.00000  9.000000e+00
mean   2010.75000  6.739094e+06
std       1.38873  3.248078e+06
min    2009.00000  3.005116e+06
25%    2009.75000  5.274553e+06
50%    2011.00000  5.573830e+06
75%    2011.25000  8.427816e+06
max    2013.00000  1.190118e+07