In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/Users/ganes/OneDrive/Desktop/FBS/Database files/Missing Value Fortune_10.csv")

In [3]:
df.head()

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
2,3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
4,5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         10 non-null     int64
 1   Date       10 non-null     str
 2   Name       9 non-null      str
 3   Companies  10 non-null     str
 4   Inception  8 non-null      float64
 5   Revenue    9 non-null      str
 6   Expenses   9 non-null      str
 7   Profit     9 non-null      float64
 8   Growth     10 non-null     str
dtypes: float64(2), int64(1), str(6)
memory usage: 852.0 bytes

In [6]:
df.describe()

             ID   Inception        Profit
count  10.00000     8.00000  9.000000e+00
mean    5.50000  2010.75000  6.739094e+06
std     3.02765     1.38873  3.248078e+06
min     1.00000  2009.00000  3.005116e+06
25%     3.25000  2009.75000  5.274553e+06
50%     5.50000  2011.00000  5.573830e+06
75%     7.75000  2011.25000  8.427816e+06
max    10.00000  2013.00000  1.190118e+07

In [10]:
df

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
2,3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
4,5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%
5,6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
6,7,Yes,Cityace,IT Service,NaN,NaN,"6,249,498 Dollars",3005116.0,6%
7,8,No,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
9,10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [12]:
df[df["ID"] > 5]

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
5,6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
6,7,Yes,Cityace,IT Service,NaN,NaN,"6,249,498 Dollars",3005116.0,6%
7,8,No,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
9,10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [14]:
df["Companies"].value_counts()

Companies
IT Service             6
Health                 2
Financial Services     1
Government Services    1
Name: count, dtype: int64

In [15]:
df["Companies"].unique()

<StringArray>
['IT Service', 'Financial Services', 'Health', 'Government Services']
Length: 4, dtype: str

In [21]:
df.dropna()

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
5,6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
7,8,No,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
9,10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [24]:
df["Profit"].fillna(100)

0     5274553.0
1    11412916.0
2     3005820.0
3     6597557.0
4         100.0
5     8427816.0
6     3005116.0
7     5573830.0
8    11901180.0
9     5453060.0
Name: Profit, dtype: float64

In [25]:
df["Companies"] = df["Companies"].replace('Health', 'Health Service')

In [26]:
df

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
2,3,No,NaN,Health Service,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
4,5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%
5,6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
6,7,Yes,Cityace,IT Service,NaN,NaN,"6,249,498 Dollars",3005116.0,6%
7,8,No,Kayelectronics,Health Service,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
9,10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%