In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(np.random.randint(30, 100, (20, 6)), columns=['m1', 'm2', 'm3', 'm4', 'm5', 'm6'])

In [3]:
df

    m1  m2  m3  m4  m5  m6
0   37  98  47  66  45  47
1   37  54  78  43  84  60
2   64  86  61  31  69  44
3   41  61  65  80  33  62
4   86  32  96  36  50  71
5   39  99  50  56  67  46
6   65  39  93  77  50  76
7   78  31  51  63  34  92
8   53  81  46  97  78  49
9   37  98  81  93  56  44
10  46  86  71  32  80  83
11  81  70  38  84  46  93
12  77  90  73  94  76  65
13  45  97  42  75  71  76
14  35  56  44  72  91  62
15  42  86  85  40  90  53
16  50  48  31  94  39  40
17  77  45  51  33  94  89
18  41  88  99  52  52  77
19  90  31  76  83  69  50

In [4]:
df2 = pd.DataFrame(np.random.randint(30, 100,(19, 2)), columns=['m7', 'm8'])
df2

    m7  m8
0   41  68
1   52  38
2   53  80
3   96  90
4   63  39
5   75  89
6   60  96
7   92  56
8   41  72
9   44  89
10  95  52
11  67  76
12  80  43
13  77  65
14  50  44
15  79  67
16  89  67
17  64  49
18  61  54

In [5]:
df3 = pd.concat([df, df2], axis=1)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   m1      20 non-null     int32
 1   m2      20 non-null     int32
 2   m3      20 non-null     int32
 3   m4      20 non-null     int32
 4   m5      20 non-null     int32
 5   m6      20 non-null     int32
dtypes: int32(6)
memory usage: 612.0 bytes

In [8]:
df3

    m1  m2  m3  m4  m5  m6    m7    m8
0   37  98  47  66  45  47  41.0  68.0
1   37  54  78  43  84  60  52.0  38.0
2   64  86  61  31  69  44  53.0  80.0
3   41  61  65  80  33  62  96.0  90.0
4   86  32  96  36  50  71  63.0  39.0
5   39  99  50  56  67  46  75.0  89.0
6   65  39  93  77  50  76  60.0  96.0
7   78  31  51  63  34  92  92.0  56.0
8   53  81  46  97  78  49  41.0  72.0
9   37  98  81  93  56  44  44.0  89.0
10  46  86  71  32  80  83  95.0  52.0
11  81  70  38  84  46  93  67.0  76.0
12  77  90  73  94  76  65  80.0  43.0
13  45  97  42  75  71  76  77.0  65.0
14  35  56  44  72  91  62  50.0  44.0
15  42  86  85  40  90  53  79.0  67.0
16  50  48  31  94  39  40  89.0  67.0
17  77  45  51  33  94  89  64.0  49.0
18  41  88  99  52  52  77  61.0  54.0
19  90  31  76  83  69  50   NaN   NaN

In [ ]:
emp = ({ 'id': [101, 102, 103, 104],
         'name': ['Ganesh', 'Vishal', 'Gaurav', 'Pranav'],
         'dname': ['IT', 'HR', 'SALES']
})
emp

{'id': [101, 102, 103, 104],
 'name': ['Ganesh', 'Vishal', 'Gaurav', 'Pranav'],
 'dname': ['IT', 'HR', 'SALES']}