In [1]:
import pandas as pd

### Series

In [2]:
s1 = pd.Series([10, 20, 30, 40])
s1

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
s1 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
s1

a    10
b    20
c    30
d    40
dtype: int64

In [4]:
s2 = pd.Series([50, 60, 70, 80], index=['d', 'e', 'f', 'g'])
s2

d    50
e    60
f    70
g    80
dtype: int64

In [5]:
s1 + s2

a     NaN
b     NaN
c     NaN
d    90.0
e     NaN
f     NaN
g     NaN
dtype: float64

In [6]:
s1.min()

np.int64(10)

In [7]:
s2.max()

np.int64(80)

In [8]:
s1.mean()

np.float64(25.0)

In [9]:
s1.sum()

np.int64(100)

In [10]:
s1.count()

np.int64(4)

In [11]:
s2.describe()

count     4.000000
mean     65.000000
std      12.909944
min      50.000000
25%      57.500000
50%      65.000000
75%      72.500000
max      80.000000
dtype: float64

In [12]:
s1.median()

np.float64(25.0)

### DataFrame

In [13]:
df = pd.DataFrame({
    "ID"   : [101, 102, 103],
    "Name" : ['Ganesh', 'Gaurav', 'Vishal'],
    "Marks": [80, 70, 75],
    "City" : ['Latur', 'Nashik', "Mumbai"]
})
df

    ID    Name  Marks    City
0  101  Ganesh     80   Latur
1  102  Gaurav     70  Nashik
2  103  Vishal     75  Mumbai

In [14]:
data = pd.read_csv("C:/Users/ganes/OneDrive/Desktop/FBS/Database files/Missing Value Fortune_10.csv")
data

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
2,3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
4,5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%
5,6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
6,7,Yes,Cityace,IT Service,NaN,NaN,"6,249,498 Dollars",3005116.0,6%
7,8,No,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
9,10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [15]:
data.set_index("ID")

,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
ID,,,,,,,,
1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%
6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
7,Yes,Cityace,IT Service,NaN,NaN,"6,249,498 Dollars",3005116.0,6%
8,No,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [16]:
data.head()

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
2,3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
4,5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%

In [17]:
data.head(2)

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%

In [18]:
data.tail()

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
5,6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
6,7,Yes,Cityace,IT Service,NaN,NaN,"6,249,498 Dollars",3005116.0,6%
7,8,No,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
9,10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [19]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         10 non-null     int64
 1   Date       10 non-null     str
 2   Name       9 non-null      str
 3   Companies  10 non-null     str
 4   Inception  8 non-null      float64
 5   Revenue    9 non-null      str
 6   Expenses   9 non-null      str
 7   Profit     9 non-null      float64
 8   Growth     10 non-null     str
dtypes: float64(2), int64(1), str(6)
memory usage: 852.0 bytes

In [23]:
data.set_index("ID",inplace=True)

In [24]:
data

,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
ID,,,,,,,,
1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%
6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
7,Yes,Cityace,IT Service,NaN,NaN,"6,249,498 Dollars",3005116.0,6%
8,No,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [27]:
data.loc[1:3]

,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
ID,,,,,,,,
1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%

In [33]:
data.iloc[0:3]

,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
ID,,,,,,,,
1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%

In [32]:
data.loc[1:3]

,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
ID,,,,,,,,
1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%

In [36]:
data.shape

(10, 8)

In [37]:
data.columns

Index(['Date', 'Name', 'Companies', 'Inception', 'Revenue', 'Expenses',
       'Profit', 'Growth'],
      dtype='str')

In [38]:
data.index

RangeIndex(start=1, stop=11, step=1, name='ID')

In [39]:
data.dtypes

Date             str
Name             str
Companies        str
Inception    float64
Revenue          str
Expenses         str
Profit       float64
Growth           str
dtype: object

In [41]:
data.describe()

        Inception        Profit
count     8.00000  9.000000e+00
mean   2010.75000  6.739094e+06
std       1.38873  3.248078e+06
min    2009.00000  3.005116e+06
25%    2009.75000  5.274553e+06
50%    2011.00000  5.573830e+06
75%    2011.25000  8.427816e+06
max    2013.00000  1.190118e+07

In [42]:
data.value_counts()

Date  Name            Companies            Inception  Revenue      Expenses           Profit      Growth
Yes   Lamtone         IT Service           2009.0     $11,757,018  6,482,465 Dollars  5274553.0   30%       1
      Mattouch        IT Service           2013.0     $14,026,934  7,429,377 Dollars  6597557.0   7%        1
      Techline        IT Service           2011.0     $13,898,119  5,470,303 Dollars  8427816.0   7%        1
No    Kayelectronics  Health               2009.0     $9,451,943   3,878,113 Dollars  5573830.0   4%        1
Yes   Ganzlax         IT Service           2011.0     $14,001,180  3,878,153 Dollars  11901180.0  18%       1
      Transtraxlax    Government Services  2011.0     $11,088,336  5,635,276 Dollars  5453060.0   7%        1
Name: count, dtype: int64

In [43]:
data.isnull()

     Date   Name  Companies  Inception  Revenue  Expenses  Profit  Growth
ID
1   False  False      False      False    False     False   False   False
2   False  False      False      False    False      True   False   False
3   False   True      False      False    False     False   False   False
4   False  False      False      False    False     False   False   False
5   False  False      False       True    False     False    True   False
6   False  False      False      False    False     False   False   False
7   False  False      False       True     True     False   False   False
8   False  False      False      False    False     False   False   False
9   False  False      False      False    False     False   False   False
10  False  False      False      False    False     False   False   False

In [44]:
data.notnull()

    Date   Name  Companies  Inception  Revenue  Expenses  Profit  Growth
ID
1   True   True       True       True     True      True    True    True
2   True   True       True       True     True     False    True    True
3   True  False       True       True     True      True    True    True
4   True   True       True       True     True      True    True    True
5   True   True       True      False     True      True   False    True
6   True   True       True       True     True      True    True    True
7   True   True       True      False    False      True    True    True
8   True   True       True       True     True      True    True    True
9   True   True       True       True     True      True    True    True
10  True   True       True       True     True      True    True    True