In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("C:/Users/ganes/OneDrive/Desktop/FBS/Database files/Missing Value Fortune_10.csv")
data.head()

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
2,3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
4,5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         10 non-null     int64
 1   Date       10 non-null     str
 2   Name       9 non-null      str
 3   Companies  10 non-null     str
 4   Inception  8 non-null      float64
 5   Revenue    9 non-null      str
 6   Expenses   9 non-null      str
 7   Profit     9 non-null      float64
 8   Growth     10 non-null     str
dtypes: float64(2), int64(1), str(6)
memory usage: 852.0 bytes

In [4]:
data.describe()

             ID   Inception        Profit
count  10.00000     8.00000  9.000000e+00
mean    5.50000  2010.75000  6.739094e+06
std     3.02765     1.38873  3.248078e+06
min     1.00000  2009.00000  3.005116e+06
25%     3.25000  2009.75000  5.274553e+06
50%     5.50000  2011.00000  5.573830e+06
75%     7.75000  2011.25000  8.427816e+06
max    10.00000  2013.00000  1.190118e+07

In [5]:
data

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
2,3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
4,5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%
5,6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
6,7,Yes,Cityace,IT Service,NaN,NaN,"6,249,498 Dollars",3005116.0,6%
7,8,No,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
9,10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [6]:
data.loc[5]

ID                           6
Date                       Yes
Name                  Techline
Companies           IT Service
Inception               2011.0
Revenue            $13,898,119
Expenses     5,470,303 Dollars
Profit               8427816.0
Growth                      7%
Name: 5, dtype: object

In [7]:
data[data['Date'] == 'Yes']

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
5,6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
6,7,Yes,Cityace,IT Service,NaN,NaN,"6,249,498 Dollars",3005116.0,6%
8,9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
9,10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [8]:
data

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
2,3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
4,5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%
5,6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
6,7,Yes,Cityace,IT Service,NaN,NaN,"6,249,498 Dollars",3005116.0,6%
7,8,No,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
9,10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [9]:
data.loc[data['Name'] == 'Kayelectronics', 'Date'] = 'Yes'

In [10]:
data

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
2,3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
4,5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%
5,6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
6,7,Yes,Cityace,IT Service,NaN,NaN,"6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
9,10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [11]:
data['Date'].unique()

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [12]:
data['Date'].value_counts()

Date
Yes    8
No     2
Name: count, dtype: int64

#### Handling missing values
1. Remove
2. Replace

In [13]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         10 non-null     int64
 1   Date       10 non-null     str
 2   Name       9 non-null      str
 3   Companies  10 non-null     str
 4   Inception  8 non-null      float64
 5   Revenue    9 non-null      str
 6   Expenses   9 non-null      str
 7   Profit     9 non-null      float64
 8   Growth     10 non-null     str
dtypes: float64(2), int64(1), str(6)
memory usage: 852.0 bytes

In [14]:
data.isnull()

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,True,False,False
2,False,False,True,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,True,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,True,True,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False

In [15]:
data.isnull().sum()

ID           0
Date         0
Name         1
Companies    0
Inception    2
Revenue      1
Expenses     1
Profit       1
Growth       0
dtype: int64

In [16]:
data.dropna()

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
5,6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
7,8,Yes,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
9,10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [17]:
data

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371",NaN,11412916.0,20%
2,3,No,NaN,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
4,5,No,Techdrill,IT Service,NaN,"$10,573,990","7,435,363 Dollars",NaN,7%
5,6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
6,7,Yes,Cityace,IT Service,NaN,NaN,"6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
9,10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [18]:
data.bfill()

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371","7,591,189 Dollars",11412916.0,20%
2,3,No,Mattouch,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
4,5,No,Techdrill,IT Service,2011.0,"$10,573,990","7,435,363 Dollars",8427816.0,7%
5,6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
6,7,Yes,Cityace,IT Service,2009.0,"$9,451,943","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
9,10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [19]:
data.ffill()

,ID,Date,Name,Companies,Inception,Revenue,Expenses,Profit,Growth
0,1,Yes,Lamtone,IT Service,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Yes,Stripfind,Financial Services,2010.0,"$12,329,371","6,482,465 Dollars",11412916.0,20%
2,3,No,Stripfind,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Yes,Mattouch,IT Service,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,7%
4,5,No,Techdrill,IT Service,2013.0,"$10,573,990","7,435,363 Dollars",6597557.0,7%
5,6,Yes,Techline,IT Service,2011.0,"$13,898,119","5,470,303 Dollars",8427816.0,7%
6,7,Yes,Cityace,IT Service,2011.0,"$13,898,119","6,249,498 Dollars",3005116.0,6%
7,8,Yes,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Yes,Ganzlax,IT Service,2011.0,"$14,001,180","3,878,153 Dollars",11901180.0,18%
9,10,Yes,Transtraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [20]:
data['Date'].replace({'Yes': 1, 'No': 0}).astype('int')

0    1
1    1
2    0
3    1
4    0
5    1
6    1
7    1
8    1
9    1
Name: Date, dtype: int64

In [21]:
data['Date'].map({'Yes':1, 'No':0})

0    1
1    1
2    0
3    1
4    0
5    1
6    1
7    1
8    1
9    1
Name: Date, dtype: int64

In [24]:
data = pd.read_csv("C:/Users/ganes/OneDrive/Desktop/FBS/Database files/student_result.csv")
data.head()

,Student ID,Section,Class,Study hrs,Sleeping hrs,Social Medic,Mobile Game,Percentage
0,1001,A,10,2,9,3,5,50
1,1002,B,10,6,8,2,0,80
2,1003,A,10,3,8,2,4,60
3,1004,C,11,0,10,1,5,45
4,1005,C,11,4,7,2,0,75

In [26]:
res = data.groupby('Class')
res

In [27]:
res.groups

{10: [0, 1, 2], 11: [3, 4, 5], 12: [6, 7, 8, 9]}

In [28]:
obj = dict(list(res))

In [29]:
obj[10]

,Student ID,Section,Class,Study hrs,Sleeping hrs,Social Medic,Mobile Game,Percentage
0,1001,A,10,2,9,3,5,50
1,1002,B,10,6,8,2,0,80
2,1003,A,10,3,8,2,4,60

In [30]:
obj[10]['Percentage'].mean()

np.float64(63.333333333333336)

In [31]:
group2 = data.groupby(['Class', 'Section'])

In [32]:
obj2 = dict(list(group2))
obj2

{(10,
  'A'):    Student ID Section  Class  Study hrs  Sleeping hrs  Social Medic  \
 0        1001       A     10          2             9             3
 2        1003       A     10          3             8             2

    Mobile Game  Percentage
 0            5          50
 2            4          60  ,
 (10,
  'B'):    Student ID Section  Class  Study hrs  Sleeping hrs  Social Medic  \
 1        1002       B     10          6             8             2

    Mobile Game  Percentage
 1            0          80  ,
 (11,
  'A'):    Student ID Section  Class  Study hrs  Sleeping hrs  Social Medic  \
 5        1006       A     11         10             7             0

    Mobile Game  Percentage
 5            0          96  ,
 (11,
  'C'):    Student ID Section  Class  Study hrs  Sleeping hrs  Social Medic  \
 3        1004       C     11          0            10             1
 4        1005       C     11          4             7             2

    Mobile Game  Percentage
 3            5          45
 4            0          75  ,
 (12,
  'A'):    Student ID Section  Class  Study hrs  Sleeping hrs  Social Medic  \
 7        1008       A     12         10             6             2

    Mobile Game  Percentage
 7            0          90  ,
 (12,
  'B'):    Student ID Section  Class  Study hrs  Sleeping hrs  Social Medic  \
 6        1007       B     12          4             6             0
 8        1009       B     12          2             8             2

    Mobile Game  Percentage
 6            0          80
 8            4          60  ,
 (12,
  'C'):    Student ID Section  Class  Study hrs  Sleeping hrs  Social Medic  \
 9        1010       C     12          6             9             1

    Mobile Game  Percentage
 9            0          85  }

In [33]:
obj[10]['Percentage'].agg(['min', 'max', 'sum', 'mean'])

min      50.000000
max      80.000000
sum     190.000000
mean     63.333333
Name: Percentage, dtype: float64